version: '3.8'
services:
  auth-db:
    image: postgres:13
    ports:
      - 5123:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pxtm0222
      POSTGRES_DB: auth
    networks:
      - auth_network
networks:
  auth_network:
